name: Voxel.Wiki Site Generation v1

on:
  #push:
  #  branches:
  #    - main 
  #pull_request:
  workflow_dispatch:

jobs:
  build:
    name: 'Build Site'
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
        with:
          lfs: false
      - name: 'Build' 
        uses: shalzz/zola-deploy-action@186b5039430ab38781dde8feaf0861bcc017413f
        env:
          BUILD_DIR: .
          BUILD_ONLY: true
          GITHUB_TOKEN: ${{ secrets.VOXEL_WIKI }}
  build_and_deploy:
    name: 'Build & Deploy Site'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
        with:
          lfs: false
      - name: 'Build & Deploy'
        uses: shalzz/zola-deploy-action@186b5039430ab38781dde8feaf0861bcc017413f
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: .
          GITHUB_TOKEN: ${{ secrets.VOXEL_WIKI }}
